---
- name: Set profiler
  hosts: 
  - midtier
  - bucket
  tags: 
  - set_profiler_hosts
  tasks:
  - name: Set profiler Hosts
    shell: cd ~/HDSearch-Multinode-Client-Conf/profiler; ./setHosts.sh 1 $(hostname | awk -F"." '{print $1}' | sed 's/node//g') $(hostname | awk -F"." '{print $1}' | sed 's/node//g')
    async: 10000 
    poll: 0
- name: Run remote profiler
  hosts: client
  tags: 
  - run_profiler
  tasks:
  - name: Run remote profiler
    shell: ~/HDSearch-Multinode-Client-Conf/scripts/startProfiler.sh {{ HOST_FILE }} {{ ITERATION }}
- name: Kill remote profiler
  hosts: 
  - bucket
  - midtier
  tags: 
  - kill_profiler
  tasks:
  - name: Kill remote profiler       
    ignore_errors: yes
    shell: cd ~/HDSearch-Multinode-Client-Conf/profiler; sudo ./profiler.sh kill_profiler
 